### ISSUE TITLE
Apple's update to their API policy - Required Reason

### ISSUE THREAD

**Issue by bagusherdi** [pichillilorenzo/flutter_inappwebview#1954] opened 2024-01-02 04:16 UTC
## Environment

Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.

## Description

Some APIs that your app uses to deliver its core functionality — in code you write or included in a third-party SDK — have the potential of being misused to access device signals to try to identify the device or user, also known as fingerprinting. Regardless of whether a user gives your app permission to track, fingerprinting is not allowed. Describe the reasons your app or third-party SDK on iOS, iPadOS, tvOS, visionOS, or watchOS uses these APIs, and check that your app or third-party SDK only uses the APIs for the expected reasons.

#Apple published a [privacy update of app submission](https://developer.apple.com/news/?id=r1henawx
#And Flutter file picker is on the [list](https://developer.apple.com/support/third-party-SDK-requirements/))

**Comment by ueman** [comment] 2024-01-02 07:14
Duplicate of #1909

**Closed** 2024-01-02 10:43 UTC
