### ISSUE TITLE
Execution failed for task ':app:processDebugResources'. > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade    > Android resource linking failed      C:\Users\samue\OneDrive\Desktop\flutterProject\one_app\build\flutter_inappwebview\intermediates\library_manifest\debug\AndroidManifest.xml:7:5-11:15: AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by techwithsam** [pichillilorenzo/flutter_inappwebview#804] opened 2021-04-15 09:10 UTC
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by techwithsam** [comment] 2021-04-15 09:13
Yeah

**Comment by pichillilorenzo** [comment] 2021-04-15 09:22
Duplicate of https://github.com/pichillilorenzo/flutter_inappwebview/issues/791

**Closed by pichillilorenzo** 2021-04-15 09:22 UTC
Labels: bug

**Comment by techwithsam** [comment] 2021-04-15 09:31
Already resolved it. Thanks
