### ISSUE TITLE
flutter_inappwebview-master/ios/Classes/InAppWebView/InAppWebView.swift

### ISSUE THREAD

**Issue by Gagandeep1408** [pichillilorenzo/flutter_inappwebview#1652] opened 2023-05-16 10:28 UTC
Please have a look getting error

**Comment by Gagandeep1408** [comment] 2023-05-16 10:31
<img width="281" alt="Screenshot 2023-05-16 at 3 57 23 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/59157362/0f5115bf-75e9-472d-a565-69d20f3aa54c">

**Comment by pichillilorenzo** [comment] 2023-05-16 12:19
duplicate of #1648

**Closed by pichillilorenzo** 2023-05-16 12:19 UTC
Labels: bug

**Comment by pichillilorenzo** [comment] 2023-05-16 12:57
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1648#issuecomment-1549202188

**Comment by AliPunjabi** [comment] 2023-08-18 07:19
@pichillilorenzo for xcode 14.3.1, mac 13 is required, what if someone doesn't have it?
