### ISSUE TITLE
xcode 16 beta3 - ambiguous use of 'evaluateJavaScript(_:completionHandler:_)' build error

### ISSUE THREAD

**Issue by Hannah-mayhew1** [pichillilorenzo/flutter_inappwebview#2221] opened 2024-07-12 15:45 UTC
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |        3.22.2       |
| Plugin version        |        6.0.0       |
| Android version       |        x       |
| iOS version           |       18      |
| macOS version         |        x       |
| Xcode version         |        16 beta 3       |
| Google Chrome version |        x       |

Device information: 

## Description

**Expected behavior:** 
Build successful

**Current behavior:** 
![Screenshot 2024-07-12 at 16 43 55](https://github.com/user-attachments/assets/3f8ad010-809f-48f3-9b8b-f36eec9b4fb2)

**Notes** 
This is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

**Comment by Hannah-mayhew1** [comment] 2024-07-12 15:52
[Linked issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2201)

**Comment by allentown521** [comment] 2024-07-19 16:40
same here

**Comment by dn1t** [comment] 2024-07-20 11:28
Same error also occurs in flutter_inappwebview_macos (macOS 15)

**Comment by Mounix99** [comment] 2024-07-20 14:01
+1

**Comment by frapeti** [comment] 2024-07-21 01:27
+1

Broken build on iOS

**Comment by Hannah-mayhew1** [comment] 2024-07-22 11:09
FYI, this is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

**Comment by allentown521** [comment] 2024-07-22 12:30
> FYI, this is specifically an incompatibility with xcode16 and not iOS18. Xcode 16 is needed to install iOS18 simulators, however iOS18 simulators will run on xcode15. I was able to bypass the issue by rolling back xcode16 to 15.4 and running iOS18 there.

Yes, this is a temporary solution, next year the appstore will force the use of xcode16, will still face this problem, the library has been more than half a year without merging code!

**Comment by aokisinn** [comment] 2024-07-25 13:44
Is this being fixed?

**Comment by ConnorDykes** [comment] 2024-08-07 15:33
I updated Mac OS to beta versions and it won't let me downgrade to Xcode 15.4 now. I am stuck with Xcode 16, Any help would be appreciated.

**Comment by Mounix99** [comment] 2024-08-07 15:43
@ConnorDykes  this should work
```dart
dependency_overrides:
  url_launcher_ios: 6.3.1
```

**Comment by landonmr** [comment] 2024-08-14 17:18
same error, the dependency override didn't work for me, any update on this issue?

**Comment by mubahood** [comment] 2024-08-20 07:21
I clicked on the error, and I deleted one like this, then it worked!

```
 public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
        if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
            if let completionHandler = completionHandler {
                completionHandler(nil, nil)
            }
            return
        }
        super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
    } 
```

**Comment by ConnorDykes** [comment] 2024-08-28 17:01
just updated to beta 6 and im getting this issue again

**Comment by ConnorDykes** [comment] 2024-08-28 18:25
> I clicked on the error, and I deleted one like this, then it worked!
> 
> ```
>  public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
>         if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
>             if let completionHandler = completionHandler {
>                 completionHandler(nil, nil)
>             }
>             return
>         }
>         super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
>     } 
> ```

what do you mean you deleted, when I delete it it give me errors

**Comment by tnitsiri** [comment] 2024-08-30 05:29
```
dependencies:
  flutter_inappwebview:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
```

```
dependency_overrides:
  flutter_inappwebview_platform_interface:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_platform_interface
  flutter_inappwebview_android:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_android
  flutter_inappwebview_ios:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
  flutter_inappwebview_macos:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
  flutter_inappwebview_web:
    git:
      url: https://github.com/GabriellArthur/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_web

```

**Comment by tnitsiri** [comment] 2024-08-30 05:30
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2201#issuecomment-2320102520

**Comment by tinaroh** [comment] 2024-09-13 06:17
I noticed someone put out a fix for this, which is to update the signature of `evaluateJavaScript` https://github.com/pichillilorenzo/flutter_inappwebview/pull/2274

For now I'm overriding with it in `pubspec.yaml`:
```
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios
```

**Comment by andychucs** [comment] 2024-09-13 06:38
Just like what tinaroh commented. 

I make a little different changes based with other submit. I keep the override function `evaluateJavaScript` as public instead to delete or change as open. 

Also can use like following:
```
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
```

**Comment by qwertylolman** [comment] 2024-09-18 11:53
the xcode16 release is available, so this issue is a kind of critical. any updates?

**Comment by nabiarshad** [comment] 2024-09-18 14:02
same issue after updating to Mac OS sequoia.
Xcode Version 16.0 (16A242d)

**Comment by Daniel-eXeX** [comment] 2024-09-18 14:05
Seconding this. I'm now encountering this issue after XCode just auto-updated. Until a fix comes out, it appears that downgrading to XCode 15.4 will work around the issue.

For those mentioning the fork made by andychucs, it doesn't seem like it works (or I set it up wrong). I still got the exception even after adding the fork as a dependency override.

**Comment by qwertylolman** [comment] 2024-09-18 14:11
> downgrading to XCode 15.4 will work around the issue.

are you able to downgrade the xcode? i cannot, as my macos also updated to sequoia. it just shows an error 'in order to use xcode you need to update to the latest version'

**Comment by Daniel-eXeX** [comment] 2024-09-18 14:49
> are you able to downgrade the xcode? i cannot, as my macos also updated to sequoia. it just shows an error 'in order to use xcode you need to update to the latest version'

I was about to come back to comment on this. I was talking to a colleague who said that he could not downgrade because he'd updated his OS version. If you've already upgraded it, then you'll need another solution.

(As such, I'm now trying to get things working with XCode 16.0 again... 15.4 is a very temporary solution)

**Comment by rania-run** [comment] 2024-09-18 21:38
I have the same issue, this temporary solution works for me.

> Just like what tinaroh commented.
> 
> I make a little different changes based on other pr. I keep the override function `evaluateJavaScript` as public instead of delete or change as open.
> 
> Also can use like following:
> 
> ```
>   flutter_inappwebview_ios:
>     git:
>       url: https://github.com/andychucs/flutter_inappwebview.git
>       ref: master
>       path: flutter_inappwebview_ios
> ```

**Comment by scriptam** [comment] 2024-09-19 21:46
For those looking for a fast workaround for `Xcode 16.0 (16A242d)`, the following is worth a consideration: <https://github.com/pichillilorenzo/flutter_inappwebview/pull/2274#issue-2523140652>

Credit and thanks go to @andychucs

Add the following to your `pubspec.yaml`

```yaml
dependencies:
  # rest of your dependencies ...
  flutter_inappwebview: ^6.0.0 

# Add the following dependency overrides for iOS & macOS, as needed -->
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

  flutter_inappwebview_macos:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
# <--
```

**Comment by amit-iconflux** [comment] 2024-09-23 09:25
+1

**Comment by aibekdv** [comment] 2024-09-23 12:15
+1

**Comment by thomasAlfonsoDC1** [comment] 2024-09-23 13:12
+1

**Comment by scriptam** [comment] 2024-09-23 14:32
Latest release `6.1.0` is [here](https://github.com/pichillilorenzo/flutter_inappwebview/releases/tag/v6.1.0), published at [pub.dev](https://pub.dev/packages/flutter_inappwebview/versions/6.1.0+1) too. 

Confirmed: <https://github.com/pichillilorenzo/flutter_inappwebview/commit/ac5d77d7741d4a56bacf4e4f92c2a6db693ff0d9> addresses `XCode 16` build error.

Note: If your pod dependency versions are not up-to-date (i.e. `OrderedSet`), you can update the CocoaPods specs with `pod repo update`

Thanks @pichillilorenzo

**Comment by VB10** [comment] 2024-09-23 14:37
I have updated the new version, but it is not working. (^6.1.0+1) I'm still getting this error: @pichillilorenzo  

<img width="536" alt="image" src="https://github.com/user-attachments/assets/1425012c-5222-4634-b4bb-2797009eec7c">

**Comment by paulhwangfti** [comment] 2024-09-23 17:31
> I have updated the new version, but it is not working. (^6.1.0+1) I'm still getting this error: @pichillilorenzo
> 
> <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/17102578/369923500-1425012c-5222-4634-b4bb-2797009eec7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTI5NjgsIm5iZiI6MTcyNzExMjY2OCwicGF0aCI6Ii8xNzEwMjU3OC8zNjk5MjM1MDAtMTQyNTAxMmMtNTIyMi00NjM0LWI0YmItMjc5NzAwOWVlYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE3MzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYzk1ZTc1MDQwODVmMDM4OGUyZmRmNTFkYTFlMTk0YjM4NTc0ZjRlNTVmZjZkNDFhM2FhNzBiYTI4MWUwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAmgYUfDoxP7R2U-JRUhbPccF5bWzYUzIOx0c0hz7F8">

Likewise. Updated to the new version (^6.1.0+1) and I still receive the same error as well.

**Comment by pichillilorenzo** [comment] 2024-09-24 11:11
Try to force the upgrade of the plugin to 6.1.0, run flutter clean and run again also `pod install` inside your iOS folder (probably you need to delete also the Podfile.lock file)

**Closed by pichillilorenzo** 2024-09-24 11:11 UTC
Labels: bug

**Comment by andynewman10** [comment] 2024-09-24 11:38
@pichillilorenzo I did it, but maybe I did it wrong?

Is the following way to operate 'bullet-proof'?
```
$ flutter clean
$ cd ios
$ rm -rf Pods
$ rm Podfile.lock
$ pod repo remove trunk
$ flutter pub get
$ flutter build ios --config-only # needed to re-generate Podfile, right?
$ pod install --repo-update # Do I need to do 'pod setup' before?
```

**Comment by pichillilorenzo** [comment] 2024-09-24 12:05
I was able to update the dependencies of the https://github.com/pichillilorenzo/flutter_browser_app app and I didn't have any problems on iOS.
Be sure to have `flutter_inappwebview: ^6.1.0+1` as your dependency in your `pubspec.yaml`. file.
Then, try this way:
```
$ flutter clean
$ flutter pub get
$ cd ios
$ rm Podfile.lock
$ pod install
```
and run your app on iOS.

**Comment by Tobi696** [comment] 2024-09-24 12:57
still got the issue in 6.1.0+1

**Comment by Mahmoudhodhod** [comment] 2024-09-24 14:08
### Step 1: Clone BoringSSL Manually
1. Open Terminal.
2. Navigate to a directory where you want to clone BoringSSL (e.g., `~/Documents`):

   ```bash
   cd ~/Documents
   ```

3. Clone the repository:

   ```bash
   git clone https://github.com/google/boringssl.git
   ```

### Step 2: Specify the Local Path in Your Podfile
1. Open your Podfile in your Flutter project's `ios` directory. You can use a text editor like nano, vim, or any graphical text editor:

   ```bash
   cd ios
   nano Podfile
   ```

2. Locate the line for `BoringSSL-GRPC` and modify it to specify the local path. Replace the existing line with:

   ```ruby
   pod 'BoringSSL-GRPC', :path => '../Documents/boringssl'
   ```

   Adjust the path based on where you cloned BoringSSL relative to your Podfile.

### Step 3: Create the Podspec File
If you encounter an error indicating that CocoaPods couldn't find a .podspec file for BoringSSL-GRPC, follow these steps:

1. Navigate to the BoringSSL directory:

   ```bash
   cd ../boringssl
   ```

2. Create a new file named `BoringSSL-GRPC.podspec`:

   ```bash
   nano BoringSSL-GRPC.podspec
   ```

3. Copy and paste the following content into the `BoringSSL-GRPC.podspec` file:

   ```ruby
   Pod::Spec.new do |s|
     s.name         = 'BoringSSL-GRPC'
     s.version      = '0.0.32'  # Update this line if necessary
     s.summary      = 'BoringSSL forked from OpenSSL.'
     s.description  = <<-DESC
       BoringSSL is a fork of OpenSSL that is designed to meet the needs of Google and its users. 
       It is a C library that provides cryptographic operations.
     DESC
     s.homepage     = 'https://boringssl.googlesource.com/boringssl'
     s.license      = { :file => 'LICENSE' }
     s.author       = { 'Google' => 'https://www.google.com/' }
     s.source       = { :git => 'https://boringssl.googlesource.com/boringssl.git', :tag => s.version.to_s }
     s.platform     = :ios, '9.0'
     s.source_files  = 'include/**', 'crypto/**', 'ssl/**'
   end
   ```

4. Save and close the file.

### Step 4: Clean and Re-Install Pods
To ensure everything is in sync, follow these steps:

1. Clean the Pod Cache:

   ```bash
   pod cache clean --all
   ```

2. Delete the Pods folder and Podfile.lock:

   ```bash
   rm -rf Pods Podfile.lock
   ```

3. Re-Install Pods:

   ```bash
   pod install
   ```

---

**Comment by andynewman10** [comment] 2024-09-24 14:10
@pichillilorenzo it does not work. It's 100% sure.

I triple checked everything, and your flutter_inappwebview package cannot be used on Xcode 15.x. It's that simple.

The error is invariably:

```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1431:25
```
I tried resetting Xcode in all possible and imaginable ways, upgrading to Ventura 13.7 (released yesterday), of course recreating all Pods and everything, all I managed to do was to get the above-mentioned error, with the addition of the following errors, too:
```
Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1035:20

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1038:16

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1047:20

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1050:16

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1327:25

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:1912:8

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:2859:22

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/andy/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.1.0/ios/Classes/InAppWebView/InAppWebView.swift:2870:22
```

The only (not really cool) workaround is to use this solution:

https://github.com/pichillilorenzo/flutter_inappwebview/pull/2274

making sure `ref: xcode-15-fix` is used, and not `ref: master` (otherwise it won't work).

Again, I am not mentioning here a problem with Xcode 16, just Xcode 15.x. **Your package no longer works with Xcode 15 as it is currently published in pub.dev.**

I strongly suggest that you look at the above listed 'xcode-15-fix' fix, and apply it to your codebase, in addition to the fix for Xcode 16. Many people still use Xcode 15 and still will for a while.

**Comment by andynewman10** [comment] 2024-09-24 14:46
@pichillilorenzo if I can help (testing on my setup), let me know. The thing is, I am not too familiar with iOS/Swift programming.

My iPhoneOS.platform SDK version is 17.2 (latest version available for Xcode on Ventura), as shown in

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/version.plist
```

Maybe you are using a different SDK version?

I wonder if conditional compilation directives couldn't be used here? `if @available(iOS 18, *)` or `if compiler(>=5.xxx)`? This way, the code would work with both Xcode 15 and 16 (I mean... SDK 17.2 and 18?).

**Comment by pichillilorenzo** [comment] 2024-09-24 17:52
@andynewman10 currently the new version works only with XCode >= 16.0, so it won't work on XCode 15.x
I thought you were having the problem with XCode 16, but if you are using XCode 15, then it won't work.
The Apple/Webkit team literally changed the WKWebView.evaluateJavaScript signature, which this plugin overrides.
If possible, you should update to XCode 16.0.

Currently, I haven't found a compilation directive to check XCode versions or if there is something that could be used to support both XCode 15 and 16.

**Comment by pichillilorenzo** [comment] 2024-09-24 17:58
Maybe `__IPHONE_OS_VERSION_MAX_ALLOWED` or `__IPHONE_OS_VERSION_MIN_REQUIRED`  could be used?
Check: https://stackoverflow.com/a/8050536/4637638

**Comment by pichillilorenzo** [comment] 2024-09-24 18:29
Moved to: https://github.com/pichillilorenzo/flutter_inappwebview/issues/2288

**Comment by pichillilorenzo** [comment] 2024-09-25 01:14
Released new `flutter_inappwebview_ios` and `flutter_inappwebview_macos` version `1.1.0+1` with the fix! I was able to use `#if compiler(>=6.0)` for Swift.
XCode 16 uses the Swift 6.0 compiler (more info here: https://xcodereleases.com/), so in the "else" statement we can use the "old" version of the "evaluateJavaScript" method.

You can run `flutter pub upgrade` to update the dependencies.

**Comment by akshayAtDWI** [comment] 2024-09-29 11:07
> I updated Mac OS to beta versions and it won't let me downgrade to Xcode 15.4 now. I am stuck with Xcode 16, Any help would be appreciated.

Stucked in the same situatuin, if you find any solution, please let me know.

**Comment by pichillilorenzo** [comment] 2024-09-29 11:12
@akshayAtDWI updated the `flutter_inappwebview` plugin to the latest version.

**Comment by ybbond** [comment] 2024-10-07 12:07
pardon to resurrect the issue @pichillilorenzo, but is there any other alternative to upgrading `flutter_inappwebview`  (including to manually edit Podfile dependency code) ?

The thing is to update the pub package require us to upgrade Flutter, which we cannot do in the meantime.

Thanks before

**Comment by bitspad** [comment] 2024-10-13 22:25
> I clicked on the error, and I deleted one like this, then it worked!
> 
> ```
>  public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
>         if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
>             if let completionHandler = completionHandler {
>                 completionHandler(nil, nil)
>             }
>             return
>         }
>         super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
>     } 
> ```

This is the best solution, it works for me.

**Comment by Aladdin-Shaker** [comment] 2024-10-25 22:15
Has anyone tried to solve it, please?

Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (6 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
Xcode 16

**Comment by pichillilorenzo** [comment] 2024-10-25 22:48
@Aladdin-Shaker the latest plugin works with Flutter 3.24+. If you can update Flutter, then you can update also the plugin.

**Comment by Aladdin-Shaker** [comment] 2024-10-25 23:20
> @Aladdin-Shaker the latest plugin works with Flutter 3.24+. If you can update Flutter, then you can update also the plugin.

thdo you mean flutter_inappwebview ?

**Comment by Aladdin-Shaker** [comment] 2024-10-25 23:22
> @Aladdin-Shaker yes 👍

Thanks :)

**Comment by chalananupun** [comment] 2024-11-08 06:29
> I clicked on the error, and I deleted one like this, then it worked!
> 
> ```
>  public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
>         if let applePayAPIEnabled = options?.applePayAPIEnabled, applePayAPIEnabled {
>             if let completionHandler = completionHandler {
>                 completionHandler(nil, nil)
>             }
>             return
>         }
>         super.evaluateJavaScript(javaScriptString, completionHandler: completionHandler)
>     } 
> ```

This is worked me. Thanks :heart:

**Comment by Aladdin-Shaker** [comment] 2024-11-25 09:41
> is there new plugin update with this fix?

No, I have upgraded the Flutter version with the packages

**Comment by pichillilorenzo** [comment] 2024-11-25 09:47
Yes, you need to update the plugin @qwertylolman 

> the latest plugin works with Flutter 3.24+. If you can update Flutter, then you can update also the plugin.
