### ISSUE TITLE
Accessibility Android

### ISSUE THREAD

**Issue by bruzzers** [pichillilorenzo/flutter_inappwebview#1694] opened 2023-06-14 13:01 UTC
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.7.11       |
| Plugin version  |       5.7.2+3        |
| Android version |      33         |
| iOS version     |         x      |
| macOS version   |     x          |
| Xcode version   |        x       |

Device information: all Android

## Description

Using this version of the plugin when the talkback recognise the web view, when swipe talkback not move to web page elements but to the next element of the app. If I move to 5.7.1+2 version of plugin it work correctly. I think the change in 5.7.2 broke something inside the accessibility and talkback.

**Comment by Ray13** [comment] 2023-07-04 15:55
Hi, I too have the same problem.

The problem is systematic and we have not found a solution online.
Accessibility not working, other flutter webview plugins read accessibility correctly.

**Comment by lirantzairi** [comment] 2023-09-30 10:48
Have the same problem too, had to revert back to v5.7.1+2

**Comment by ajanec01** [comment] 2024-02-29 13:21
Hi @pichillilorenzo 
The issue is cased by the removal of the `options.useHybridComposition` constraint in [c2ce274](https://github.com/pichillilorenzo/flutter_inappwebview/commit/c2ce274754be06c879f3fe733e4429ec70be4e94). I've had some experience with screen readers and noticed that they can be a bit fussy when working with an overflow. It looks like it's something to do with `webView.setLayoutParams`.

**Comment by moheb-badawy** [comment] 2024-08-08 09:07
Semantics is completely broken for inAppWebView on Android and iOS.

Could you please provide an update on when this problem might be resolved, @pichillilorenzo ?

**Comment by Velliane** [comment] 2024-09-19 14:26
Hi,
I have the problem too with version 6.0.0. Can this be resolved ?

**Comment by pichillilorenzo** [comment] 2024-11-10 11:26
I'm not able to reproduce the issue. I'm using latest version of the plugin and Flutter 3.24.3.
This is a real Android device and Talkback is working correctly:

https://github.com/user-attachments/assets/fd622a54-97a8-492e-be15-1dccce4aa268

**Comment by ueman** [comment] 2024-11-12 08:54
@pichillilorenzo Did you at any point tap directly into the webview? In that case it works for me, but I can't get into the webview by using exclusively the talk back gestures.

**Comment by pichillilorenzo** [comment] 2024-11-12 21:17
It will be fixed with version `6.2.0-beta.2`.
You can try the master branch, thanks.

**Closed** 2024-11-12 21:16 UTC
Labels: bug

**Comment by pichillilorenzo** [comment] 2024-11-26 21:08
Released new version `6.2.0-beta.2` with the fix.

**Comment by bossPsw** [comment] 2024-11-29 01:44
> 해당 버그를 수정하여 새로운 버전을 출시했습니다 `6.2.0-beta.2`.
Even after updating, TalkBack still cannot recognize the content. The same issue persists even when turning TalkBack on and off within the app.

**Comment by pichillilorenzo** [comment] 2024-11-29 01:52
@bossPsw post minimal code to reproduce the issue and a screen recording, thanks.

**Comment by pichillilorenzo** [comment] 2024-11-29 10:11
I was able to reproduce the issue: TalkBack works correctly the first time is activated, but if you turn it off and on again while the Flutter app is still running, TalkBack will not recognize the WebView (Flutter PlatformView) anymore.

It seems to be related to how Flutter PlatformView currently works under the hood.
Indeed, here is the official Flutter issue about it: https://github.com/flutter/flutter/issues/158004
It seems that the Flutter team should fix it.

**Comment by bossPsw** [comment] 2024-11-29 10:22
Thank you for your answer. I always use flutter inappview well. I wish for
your continued development

2024년 11월 29일 (금) 19:11, Lorenzo Pichilli ***@***.***>님이 작성:
