### ISSUE TITLE
Module ‘flutter_inappwebview’ not found in Xcode 

### ISSUE THREAD

**Issue by Phabbyrich** [pichillilorenzo/flutter_inappwebview#773] opened 2021-04-01 11:02 UTC
Does anyone have a solution to this?

**Comment by pichillilorenzo** [comment] 2021-04-01 11:33
Duplicate of https://github.com/pichillilorenzo/flutter_inappwebview/issues/458

**Closed by pichillilorenzo** 2021-04-01 11:33 UTC
