### ISSUE TITLE
iOS Fatal Crash

### ISSUE THREAD

**Issue by tal412** [pichillilorenzo/flutter_inappwebview#1894] opened 2023-12-04 07:32 UTC
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.16          |
| Plugin version  |     ^6.0.0-beta.30          |
| Android version |       -        |
| iOS version     |        17.1.2       |
| macOS version   |       -        |
| Xcode version   |       -        |

Device information: 

## Description
What I know is that after a long time the app is in the background I get back to it and open the WebView, and then it just crashes. Absolute crash without notice. I was not able to get the full log because the crash is too random, but I was able the get the Crashlytics report.
It happened to me once while the device was connected but I got no log at all. The app just disconnected from the debugger. 

## Steps to reproduce

Again, nothing very specific. It happens on the build that's all I know.
Below is my code:

```
  InAppWebView _buildWebView() {

    var browserModel = Provider.of<BrowserModel>(context, listen: true);
    var settings = browserModel.getSettings();
    var currentWebViewModel = Provider.of<WebViewModel>(context, listen: true);

    if (Platform.isAndroid) {
      InAppWebViewController.setWebContentsDebuggingEnabled(
          settings.debuggingEnabled);
    }

    var initialSettings = widget.webViewModel.settings!;
    initialSettings.useOnDownloadStart = true;
    initialSettings.useOnLoadResource = true;
    initialSettings.useShouldOverrideUrlLoading = true;
    initialSettings.javaScriptCanOpenWindowsAutomatically = true;
    initialSettings.userAgent =
        "Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36";
    initialSettings.transparentBackground = true;

    initialSettings.safeBrowsingEnabled = true;
    initialSettings.disableDefaultErrorPage = true;
    initialSettings.supportMultipleWindows = true;
    initialSettings.verticalScrollbarThumbColor =
        const Color.fromRGBO(0, 0, 0, 0.5);
    initialSettings.horizontalScrollbarThumbColor =
        const Color.fromRGBO(0, 0, 0, 0.5);

    initialSettings.allowsLinkPreview = false;
    initialSettings.isFraudulentWebsiteWarningEnabled = true;
    initialSettings.disableLongPressContextMenuOnLinks = true;
    initialSettings.allowingReadAccessTo = WebUri('file://$WEB_ARCHIVE_DIR/');


    return InAppWebView(
      initialUrlRequest: URLRequest(url: widget.webViewModel.url),
      initialSettings: initialSettings,
      windowId: widget.webViewModel.windowId,
      pullToRefreshController: _pullToRefreshController,
      findInteractionController: _findInteractionController,

      onWebViewCreated: (controller) async {


        initialSettings.transparentBackground = false;
        await controller.setSettings(settings: initialSettings);

        _webViewController = controller;
        widget.webViewModel.webViewController = controller;
        widget.webViewModel.pullToRefreshController = _pullToRefreshController;
        widget.webViewModel.findInteractionController = _findInteractionController;

        Future<InAppWebViewSettings?> settingsFuture = controller.getSettings();
        settingsFuture.then((settings) {
          if (_isDisposed)
            return;

          if (settings != null) {
            widget.webViewModel.settings = settings;
          }
        }).catchError((error) {
          debugPrint("Error getting settings: $error");
        });

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },

      onLoadStop: (controller, url) async {

        if(_isDisposed)
          return;
        
        _pullToRefreshController?.endRefreshing();

        widget.webViewModel.url = url;
        widget.webViewModel.favicon = null;
        widget.webViewModel.loaded = true;

        var sslCertificateFuture = _webViewController?.getCertificate();
        var titleFuture = _webViewController?.getTitle();
        var faviconsFuture = _webViewController?.getFavicons();

        var sslCertificate = await sslCertificateFuture;
        if (sslCertificate == null && !Util.isLocalizedContent(url!)) {
          widget.webViewModel.isSecure = false;
        }

        widget.webViewModel.title = await titleFuture;

        List<Favicon>? favicons = await faviconsFuture;
        if (favicons != null && favicons.isNotEmpty) {
          for (var fav in favicons) {
            if (widget.webViewModel.favicon == null) {
              widget.webViewModel.favicon = fav;
            } else {
              if ((widget.webViewModel.favicon!.width == null &&
                      !widget.webViewModel.favicon!.url
                          .toString()
                          .endsWith("favicon.ico")) ||
                  (fav.width != null &&
                      widget.webViewModel.favicon!.width != null &&
                      fav.width! > widget.webViewModel.favicon!.width!)) {
                widget.webViewModel.favicon = fav;
              }
            }
          }
        }

        if (isCurrentTab(currentWebViewModel)) {
          widget.webViewModel.needsToCompleteInitialLoad = false;
          currentWebViewModel.updateWithValue(widget.webViewModel);

          var screenshotData = _webViewController
              ?.takeScreenshot(
                  screenshotConfiguration: ScreenshotConfiguration(
                      compressFormat: CompressFormat.JPEG, quality: 20))
              .timeout(
                const Duration(milliseconds: 1500),
                onTimeout: () => null,
              );

          screenshotData?.then((screenshotData) {
            if (_isDisposed) {
              return;
            }

            widget.webViewModel.screenshot = screenshotData;
          }).catchError((error) {
            // Handle any errors here.
            debugPrint("Error taking screenshot: $error");
          });
        }
      },
      onProgressChanged: (controller, progress) {
        if (progress == 100) {
          _pullToRefreshController?.endRefreshing();
        }

        widget.webViewModel.progress = progress / 100;

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },
      onUpdateVisitedHistory: (controller, url, androidIsReload) async {
        widget.webViewModel.url = url;
        widget.webViewModel.title = await _webViewController?.getTitle();

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },

      onLoadResource: (controller, resource) {
        widget.webViewModel.addLoadedResources(resource);

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },
      shouldOverrideUrlLoading: (controller, navigationAction) async {
        var url = navigationAction.request.url;

        if (url != null &&
            !["http", "https", "file", "chrome", "data", "javascript", "about"]
                .contains(url.scheme)) {
          if (await canLaunchUrl(url)) {
            // Launch the App
            await launchUrl(
              url,
            );
            // and cancel the request
            return NavigationActionPolicy.CANCEL;
          }
        }

        return NavigationActionPolicy.ALLOW;
      },

      onReceivedError: (controller, request, error) async {
        var isForMainFrame = request.isForMainFrame ?? false;
        if (!isForMainFrame) {
          return;
        }

        _pullToRefreshController?.endRefreshing();

        if (Platform.isIOS && error.type == WebResourceErrorType.CANCELLED) {
          // NSURLErrorDomain
          return;
        }

        var errorUrl = request.url;

        _webViewController?.loadData(data: """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
    ${await InAppWebViewController.tRexRunnerCss}
    </style>
    <style>
    .interstitial-wrapper {
        box-sizing: border-box;
        font-size: 1em;
        line-height: 1.6em;
        margin: 0 auto 0;
        max-width: 600px;
        width: 100%;
    }
    </style>
</head>
<body>
    ${await InAppWebViewController.tRexRunnerHtml}
    <div class="interstitial-wrapper">
      <h1>Website not available</h1>
      <p>Could not load web pages at <strong>$errorUrl</strong> because:</p>
      <p>${error.description}</p>
    </div>
</body>
    """, baseUrl: errorUrl, historyUrl: errorUrl);

        widget.webViewModel.url = errorUrl;
        widget.webViewModel.isSecure = false;

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },
      onTitleChanged: (controller, title) async {
        widget.webViewModel.title = title;

        if (isCurrentTab(currentWebViewModel)) {
          currentWebViewModel.updateWithValue(widget.webViewModel);
        }
      },
      onCreateWindow: (controller, createWindowRequest) async {
        var webViewTab = WebViewTab(
          key: GlobalKey(),
          webViewModel: WebViewModel(
              url: WebUri("about:blank"),
              windowId: createWindowRequest.windowId),
        );

        browserModel.addTab(webViewTab);

        return true;
      },
      onCloseWindow: (controller) {
        if (_isWindowClosed) {
          return;
        }
        _isWindowClosed = true;
        if (widget.webViewModel.tabIndex != null) {
          browserModel.closeTab(widget.webViewModel.tabIndex!);
        }
      },
      onPermissionRequest: (controller, permissionRequest) async {
        return PermissionResponse(
            resources: permissionRequest.resources,
            action: PermissionResponseAction.GRANT);
      },
    );
  }
```

## Images 
<img width="1178" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/36299714/092b26f2-2630-4126-8b6f-84b22f03563e">

## The relevant stack trace:

```
Crashed: com.apple.root.background-qos
0  libswiftCore.dylib             0x400034 swift_isUniquelyReferenced_nonNull_native + 38
1  flutter_inappwebview_ios       0x4d798 $s24flutter_inappwebview_ios12InAppWebViewC03webG0_10didReceive17completionHandlerySo05WKWebG0C_So28NSURLAuthenticationChallengeCySo016NSURLSessionAuthO11DispositionV_So15NSURLCredentialCSgtctFyyYbcfU3_ + 380
2  flutter_inappwebview_ios       0x4d820 $sIegh_IeyBh_TR + 28
3  libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x4300 _dispatch_client_callout + 20
5  libdispatch.dylib              0x15dbc _dispatch_root_queue_drain + 864
6  libdispatch.dylib              0x163ec _dispatch_worker_thread2 + 156
7  libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
8  libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

**Comment by Manuito83** [comment] 2023-12-05 09:48
Thanks @tal412.

I was about to report the same. I've been able to trace this down to beta >= 26. I'm still trying to change a few things here and there to understand if Flutter 3.16 could also be affecting this...?

**Comment by pichillilorenzo** [comment] 2023-12-05 10:10
Also, which version of iOS is affected?

**Comment by pichillilorenzo** [comment] 2023-12-05 10:21
From the report, it seems the crash is caused by this line:                     [InAppWebView.sslCertificatesMap[challenge.protectionSpace.host] = sslCertificate](https://github.com/pichillilorenzo/flutter_inappwebview/blob/e44c31b4560820ac8c2a019ae086e974542d0e99/flutter_inappwebview_ios/ios/Classes/InAppWebView/InAppWebView.swift#L2050)
that has been added starting from beta 26.

It was added to fix https://github.com/pichillilorenzo/flutter_inappwebview/issues/1678, so I need to find another workaround for that.

**Comment by macymind-personal** [comment] 2023-12-05 10:45
> If possible, could you post also the WebView URL that is crashing?

URL was not monitored as it occurs on live app. we received crash in Crashlytics

**Comment by pichillilorenzo** [comment] 2023-12-05 10:47
Ok, thanks for the crash report.
I will try to figure it out and update you guys as soon as possible.

**Comment by macymind-personal** [comment] 2023-12-05 10:49
Thanks! @pichillilorenzo

**Comment by AlexDochioiu** [comment] 2023-12-05 11:53
@pichillilorenzo I also started seeing this since update to beta30. Our bug reports are on iOS 16.6.1, 17.1.1, 17.1.2 (most of them), 17.0.3, ... So it's not isolated to iOS 17.1.2

**Comment by pichillilorenzo** [comment] 2023-12-05 18:53
I have released a new version `1.0.6` of the iOS implementation package `flutter_inappwebview_ios` with a possible fix for this issue.
Run `flutter upgrade` to get the latest iOS implementation package using the latest main plugin beta version `6.0.0-beta.31`.

**Comment by pichillilorenzo** [comment] 2023-12-06 11:43
Let me know if it is working, so I can close this issue.

**Comment by tal412** [comment] 2023-12-06 12:16
> Let me know if it is working, so I can close this issue.

So I have let the app be in the background for many hours and then came back to it. It didn’t crash. I believe me and the other fellows need a few more days to actually be sure. Thank you very much for the quick response.

**Comment by tal412** [comment] 2023-12-07 21:50
Seems fine to me.

**Comment by pichillilorenzo** [comment] 2023-12-07 21:53
Ok! So I’m closing this issue, thanks again.

**Closed by pichillilorenzo** 2023-12-07 21:53 UTC
Labels: bug
