### ISSUE TITLE
Unable to implement fido webauthn registration/authentication flow with the package

### ISSUE THREAD

**Issue by chunsfire** [pichillilorenzo/flutter_inappwebview#2249] opened 2024-08-12 10:18 UTC
Is there a limitation with the package that it doesn't support fido webauthn flow be it registration or authentication?

**Comment by mkhtradm01** [comment] 2024-10-23 09:09
#699 related

**Comment by pichillilorenzo** [comment] 2024-10-23 21:49
duplicate of #699

**Closed by pichillilorenzo** 2024-10-23 21:49 UTC
