### ISSUE TITLE
Pull to refresh creating problem in some webpages on Android

### ISSUE THREAD

**Issue by nilotpalkapri** [pichillilorenzo/flutter_inappwebview#719] opened 2021-03-12 19:41 UTC
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
In most of the pages new pull to refresh features working well but in few cases I noticed that when scrolling up the refresh button is appearing and refreshing the pages. For example you can check with the below page

https://api.flutter.dev/flutter/widgets/Container-class.html
Or any pages from api.flutter.dev or firebase databases

Till now I found these two sites only, where it is creating problem.

**Expected behavior:** 
Scrolling up should scroll the page until it reaches the top.
**Current behavior:** 
When scrolling up from the bottom of a page, the refresh button is appearing and refreshing the pages.
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment] 2021-03-13 11:31
I'm not able to reproduce this behavior. Tested with real iPhone using the code example in the README.md and it works.
Could you post the code you are using that causes this problem, please?

**Comment by pichillilorenzo** [comment] 2021-03-13 11:40
Ok it seems this doesn't work on Android

**Comment by pichillilorenzo** [comment] 2021-03-13 11:53
I found that the problem is related to the webpage itself.
If you inspect the webpage HTML, you can see that the one that has the scrollbar is the `<main>` HTML element and not the `<body>`, so the Android native `SwipeRefreshLayout` class thinks that the page is always on the top of the page.
That's the reason it starts to `pull-to-refresh` every time the user tries to go up.
I will check if this is fixable or not.

**Comment by pichillilorenzo** [comment] 2021-03-13 11:54
For more details: https://stackoverflow.com/questions/24658428/swiperefreshlayout-webview-when-scroll-position-is-at-top

**Comment by pichillilorenzo** [comment] 2021-03-13 12:06
Just found out that using the official Chrome App browser on mobile with https://api.flutter.dev/flutter/widgets/Container-class.html as URL, the pull-to-refresh feature is also disabled.
So, because already work this way on iOS, I think I need to disable it when the `<body>` itself has no scrollbar.

**Comment by pichillilorenzo** [comment] 2021-03-13 13:08
Fixed in the next release

**Closed** 2021-03-13 14:24 UTC
Labels: bug

**Comment by nilotpalkapri** [comment] 2021-03-13 18:09
> Fixed in the next release

Thank you very much

**Comment by nilotpalkapri** [comment] 2021-03-13 18:12
> Just found out that using the official Chrome App browser on mobile with https://api.flutter.dev/flutter/widgets/Container-class.html as URL, the pull-to-refresh feature is also disabled.
> So, because already works this way on iOS, I think I need to disable it when the `<body>` itself has no scrollbar.

You are right, I never noticed before😅

**Comment by nilotpalkapri** [comment] 2021-03-13 18:14
> Fixed in the next release

And please disable for firebase database to because there also I am facing the same problem. In firebase whole page is ok but the data portion creating problem, I mean after scrolling down the data can't go up.
