### ISSUE TITLE
stuck in loading

### ISSUE THREAD

**Issue by MagarKJ** [pichillilorenzo/flutter_inappwebview#2179] opened 2024-06-13 11:57 UTC
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |               |
| Plugin version        |               |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
![Screenshot (92)](https://github.com/pichillilorenzo/flutter_inappwebview/assets/107093272/1642f609-4185-4b68-bf2a-2eefa32ab8d7)
![Screenshot (89)](https://github.com/pichillilorenzo/flutter_inappwebview/assets/107093272/f2f67e37-771f-4257-bbca-48f00e999b16)
![Screenshot (90)](https://github.com/pichillilorenzo/flutter_inappwebview/assets/107093272/925adf35-077b-4c32-b2f9-91394db74d5a)
![Screenshot (91)](https://github.com/pichillilorenzo/flutter_inappwebview/assets/107093272/73afb0d6-4988-4839-8368-84c9cbd675c9)

## Stacktrace/Logcat   

E/flutter (26747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (26747): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (26747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (26747): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (26747): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (26747): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (26747): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (26747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (26747): )
E/flutter (26747): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (26747): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747):

**Comment by samuel-vongs** [comment] 2024-06-13 17:03
I am having the same issue, please help, i have search for solution but to no avail

**Comment by EArminjon** [comment] 2024-06-14 18:19
(please provide complete log and minimal reproductible example)

**Comment by samuel-vongs** [comment] 2024-06-19 10:44
Restarted application in 3,005ms.
D/InAppWebView(12260): Using InAppWebViewClientCompat implementation
W/cr_WebSettings(12260): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings(12260): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views(12260): Failed to handle method call
E/MethodChannel#flutter/platform_views(12260): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views(12260): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views(12260): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views(12260): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views(12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views(12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views(12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(12260): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(12260): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter/platform_views(12260): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(12260): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views(12260): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(12260): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#flutter/platform_views(12260): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(12260): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(12260): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (12260): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter (12260): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter (12260): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter (12260): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter (12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter (12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter (12260): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter (12260): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter (12260): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter (12260): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter (12260): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter (12260): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (12260): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (12260): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (12260): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (12260): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (12260): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (12260): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (12260): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (12260): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (12260): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12260): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (12260): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (12260): )
E/flutter (12260): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (12260): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (12260): <asynchronous suspension>
E/flutter (12260): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter (12260): <asynchronous suspension>
E/flutter (12260): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter (12260): <asynchronous suspension>
E/flutter (12260):
D/EGL_emulation(12260): app_time_stats: avg=28408.58ms min=28408.58ms max=28408.58ms count=1

**Comment by MagarKJ** [comment] 2024-06-20 04:56
go to your pubspec.lock file and search this package   webview_flutter_android: and change its version to  version: "3.16.1" 
this fixed my issue

**Comment by nickf2k** [comment] 2024-07-08 09:03
Is this resolved yet? I have a same issue

**Comment by TheWalkingDead2** [comment] 2024-08-06 05:33
I am encountering the same issue as described in #2179 regarding the Unknown feature SUPPRESS_ERROR_PAGE error with the flutter_inappwebview plugin. It seems to be a widespread problem, and I have attempted several solutions suggested by the community, including changing the version of webview_flutter_android, but the issue persists.

This problem significantly impacts the progress of my project, and I would greatly appreciate an official fix or more definitive guidance on resolving this issue. I can provide further logs or reproduction steps if needed.

Thank you for your efforts, and I look forward to a solution!

**Comment by adityakumars064** [comment] 2024-09-04 10:56
Adding **webview_flutter_android: 3.16.1** in **dependency_overrides** in pubspec.yaml file will work  
  
dependency_overrides:
  webview_flutter_android: 3.16.1

**Closed** 2024-11-06 04:38 UTC
Labels: bug
