### ISSUE TITLE
onClosed not considering back navigation or up button / close button in ChromeSafariBrowser when using noHistory: true

### ISSUE THREAD

**Issue by luckyhandler** [pichillilorenzo/flutter_inappwebview#1882] opened 2023-11-27 22:47 UTC
## Environment

flutter doctor                                                                                         ~/Development/uryde  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

| Technology      | Version       |
|-----------------| ------------- |
| Plugin version  |  6.0.0-beta.25 |

Device information:
OnePlus Nord (Android 12)

## Description

**Expected behavior:** 
The onClose callback does also trigger when manually closing the open ChromeSafariBrowser either by navigating back via gesture navigation / back button or by closing it via the navigation bar.

**Current behavior:** 
The onClose callback doesn't trigger when manually closing the open ChromeSafariBrowser either by navigating back via gesture navigation / back button or by closing it via the navigation bar.

## Steps to reproduce
- Implement `ChromeSafariBrowser` in own class
- Open a url with `browser.open`
- Manually close the browser 

```dart
class CloseAwareChromeSafariBrowser extends ChromeSafariBrowser {
  CloseAwareChromeSafariBrowser({
    required this.onBrowserClosed,
  });

  final VoidCallback onBrowserClosed;

  @override
  void onClosed() {
    super.onClosed(); 
    onBrowserClosed();
  }
}
```

**Comment by pichillilorenzo** [comment] 2023-11-28 00:22
I'm not able to reproduce the issue.
The `onClosed` event is called every time, by navigating back or by closing it via the navigation bar.
You should see something similar in the debug console:
```
...
[AndroidChromeSafariBrowser] (android) AndroidChromeSafariBrowser ID 182531102141742555225208 calling "onCompletedInitialLoad" using {}
[AndroidChromeSafariBrowser] (android) AndroidChromeSafariBrowser ID 182531102141742555225208 calling "onNavigationEvent" using {navigationEvent: 2}
[AndroidChromeSafariBrowser] (android) AndroidChromeSafariBrowser ID 182531102141742555225208 calling "onClosed" using {}
...
```

**Comment by luckyhandler** [comment] 2023-11-28 07:32
what happens if you use Firefox as default Browser?

**Comment by luckyhandler** [comment] 2023-11-28 10:20
My logs more look like
```
[CloseAwareChromeSafariBrowser] (android) CloseAwareChromeSafariBrowser ID 112240200103941892181734513061153558247232 calling "onCompletedInitialLoad" using {}
[CloseAwareChromeSafariBrowser] (android) CloseAwareChromeSafariBrowser ID 112240200103941892181734513061153558247232 calling "onNavigationEvent" using {navigationEvent: 2}
[CloseAwareChromeSafariBrowser] (android) CloseAwareChromeSafariBrowser ID 112240200103941892181734513061153558247232 calling "onNavigationEvent" using {navigationEvent: 6}
```

**Comment by luckyhandler** [comment] 2023-12-01 08:41
This issue doesn't happen on iOS, only on Android

**Comment by luckyhandler** [comment] 2023-12-05 10:33
@pichillilorenzo Were you able to reproduce this issue on Android?

**Comment by pichillilorenzo** [comment] 2023-12-05 10:44
@luckyhandler I didn’t take a look at it yet.
Could you post full code that you are using for the browser or create a reproducible code example? Thanks.

**Comment by luckyhandler** [comment] 2023-12-05 11:33
Find the project reproducing the bug [here](https://github.com/luckyhandler/bug_flutter_web_view)

The project sets a string when starting the app to a default value "Press the button below to open the browser".
Whenever the browser is opened it changes this text to "Opened browser!"
Whenever the `CloseAwareChromeSafariBrowser` reacts to the `onClosed` event it changes the text to "Browser closed!"

The last step never happens although the browser was closed.

**Comment by pichillilorenzo** [comment] 2023-12-05 12:09
I cannot access that project, I receive 404 not found.

**Comment by luckyhandler** [comment] 2023-12-05 12:19
ok, try again, it was private...

**Comment by pichillilorenzo** [comment] 2023-12-05 12:23
Ok! In the meantime, have you tried using an Android Emulator or another Android device? I don’t if it could be a device-specific issue

**Comment by luckyhandler** [comment] 2023-12-05 12:27
I only use real devices from different vendors
- Google Pixel 7A
- Samsung Galaxy A52 5G

- Chrome 119.0.6045.193

**Closed** 2023-12-06 11:35 UTC
Labels: bug

**Comment by pichillilorenzo** [comment] 2023-12-06 11:41
Fixed in Android-specific package implementation, use the latest beta plugin version `6.0.0-beta.31` to get the fix.
The problem was caused by using `noHistory: true`. In Android, using `noHistory` will cause `Activity.onActivityResult` to not be called, so `ChromeSafariBrowser.onClosed` won't be called.
Now there is a workaround about that to check when the android activity has been closed when using `noHistory: true`.

**Comment by luckyhandler** [comment] 2023-12-06 12:28
cool thanks!

**Comment by chnouman** [comment] 2024-07-23 14:14
@pichillilorenzo almost similar kind of issue is happening when I'm passing packageName. If I remove packageName it gives me call backs like this 
```
onCompletedInitialLoad
onClosed
```
but when I add package name the onCompletedIntialLoad method doesn't called. My purpose is when onCompetedIntialLoad is called I have to close the browser manually but seems to be some bug.
