### ISSUE TITLE
InAppWebiew getting crash in android with too large content

### ISSUE THREAD

**Issue by krishnaSoni2113** [pichillilorenzo/flutter_inappwebview#422] opened 2020-06-27 11:01 UTC
InAppWebView getting crash when adding the large of its parent container.

```
SingleChildScrollView(
                  child: Container(
                    height: 6000,
                    child: InAppWebView(
                      initialData: InAppWebViewInitialData(
                        data: "HTML CONTENT",
                      ),
                    ),
                  ),
                )
```

```
Creating a virtual display of size: [923, 8463] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2129].
E/InputMethodManager(14191): b/117267690: Failed to get fallback IMM with expected displayId=1151 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{3387dec VFEDHVCL. ........ 0,0-923,3}
D/InputMethodManager(14191): HSIFW - flag : 0 Pid : 14191
I/InputMethodManager(14191): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :io.flutter.embedding.android.FlutterView{5f3b5b5 VFE...... .F...... 0,0-1080,2214}
D/Dialog  (14191): mIsSamsungBasicInteraction = false
D/Dialog  (14191): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/MultiWindowDecorSupport(14191): updateCaptionType >> DecorView@f258cd8[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(14191): setCaptionType = 0, DecorView = DecorView@f258cd8[]
D/ViewRootImpl@22282a2[MainActivity](14191): setView = com.android.internal.policy.DecorView@f258cd8 TM=true MM=false
W/libEGL  (14191): EGLNativeWindowType 0x7d94053210 disconnect failed
D/ViewRootImpl@b5f8753[MainActivity](14191): dispatchDetachedFromWindow
D/InputTransport(14191): Input channel destroyed: 'e1eaec4', fd=283
V/InputMethodManager(14191): Not IME target window, ignoring
Lost connection to device.
```

**Comment by pichillilorenzo** [comment] 2020-06-29 15:51
Duplicate of https://github.com/pichillilorenzo/flutter_inappwebview/issues/314.

**Closed by pichillilorenzo** 2020-06-29 15:51 UTC
Labels: bug
