### ISSUE TITLE
Multiple sessions

### ISSUE THREAD

**Issue by owenkealey** [pichillilorenzo/flutter_inappwebview#371] opened 2020-06-02 07:29 UTC
Hi,

My goal is to have multiple inappwebview sessions in my app so that they each have their own state and do not share anything. I tried using UniqueKeys to distinguish between web views but it seems the cookies on the first web view are being used by the second web view. Any guidance on how to fix this?

**Comment by pichillilorenzo** [comment] 2020-06-02 10:30
I made some research to check if it is possible to do this in Android, but it seems not possible. The problem is not related to any Flutter API, such as `UniqueKeys`. Probably it is related to how Android manage cookies for all the WebViews.

**Comment by owenkealey** [comment] 2020-06-02 13:22
I am trying iOS not Android.

**Comment by owenkealey** [comment] 2020-06-02 14:51
I can do this with multiple WKWebView instances in Swift so I am wondering if it was possible with this plugin

**Comment by pichillilorenzo** [comment] 2020-06-02 23:39
Ok, I found a bug in my code for the iOS platform. I was setting some WKWebView configurations too late. This will be fixed in the next release!

It seems that to have multiple sessions on iOS, I need to use `configuration.websiteDataStore = WKWebsiteDataStore.nonPersistent()` for each `WKWebView` you want to have without sharing cookies.
This is done through the `incognito: true` option.

Now `incognito` option is broken on iOS, but I'm going to fix it right now.

**Comment by owenkealey** [comment] 2020-06-02 23:42
Awesome thank you!

**Closed** 2020-06-02 23:46 UTC

**Comment by pichillilorenzo** [comment] 2020-06-03 00:13
New version `3.3.0+3` released!

**Comment by RohitRajP** [comment] 2020-08-24 00:47
I am facing the same problem dealt with @owenkealey here.

The cookies are not stored only when there is an `incognito` version is present, which I believe would mean that maybe that feature is causing the problem.

I have tried the same code sample provided by @pichillilorenzo in this page. The same Gmail example provided, does not always persist the data all the time.
You can even try using other OAuth enabled sites such as Medium.com or similar.

@pichillilorenzo Could you please look into this?

**Comment by RohitRajP** [comment] 2020-08-24 03:05
@pichillilorenzo @owenkealey 
I experimented around a bit, and found that while in `incognito` mode, the cookies for example are wiped clean to default state, the cookies are not filled with the default values once the `incognito` mode is turned off.
What could be the reason for this?

**Comment by sarthak13gupta** [comment] 2023-02-03 08:22
> I made some research to check if it is possible to do this in Android, but it seems not possible. The problem is not related to any Flutter API, such as `UniqueKeys`. Probably it is related to how Android manage cookies for all the WebViews.

Hi , is it still not possible to have multiple inappwebview sessions without sharing state or anything ? 
I'm making a dapp wherein i have to connect with the same web3 site on two different webviews but with different wallets .... can u help me with that?
